repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-check
        args: [--fix]
        types: [python]
      - id: ruff-format
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        args:
          [
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --disallow-untyped-calls,
            --ignore-missing-imports,
            --install-types,
          ]
        exclude: tests/
        additional_dependencies:
          - types-click
          - types-requests
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
