model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val_acc"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val_acc"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1
